// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: address.sql

package sqlc

import (
	"context"
	"database/sql"
)

const CreateAddress = `-- name: CreateAddress :one
INSERT INTO address (jalan, rt, rw, kota, postal_code)
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type CreateAddressParams struct {
	Jalan      string `json:"jalan"`
	Rt         string `json:"rt"`
	Rw         string `json:"rw"`
	Kota       string `json:"kota"`
	PostalCode string `json:"postal_code"`
}

func (q *Queries) CreateAddress(ctx context.Context, arg CreateAddressParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, CreateAddress,
		arg.Jalan,
		arg.Rt,
		arg.Rw,
		arg.Kota,
		arg.PostalCode,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const FindAdressByID = `-- name: FindAdressByID :one
SELECT id, jalan, rt, rw, kota, postal_code FROM address WHERE id = $1
`

func (q *Queries) FindAdressByID(ctx context.Context, id int32) (*Address, error) {
	row := q.db.QueryRowContext(ctx, FindAdressByID, id)
	var i Address
	err := row.Scan(
		&i.ID,
		&i.Jalan,
		&i.Rt,
		&i.Rw,
		&i.Kota,
		&i.PostalCode,
	)
	return &i, err
}

const UpdateAddress = `-- name: UpdateAddress :exec
UPDATE address 
SET
jalan = COALESCE($2, jalan),
rt = COALESCE($3, rt),
rw = COALESCE($4, rw),
kota = COALESCE($5, kota),
postal_code = COALESCE($6, postal_code)
WHERE id = $1
`

type UpdateAddressParams struct {
	ID         int32          `json:"id"`
	Jalan      sql.NullString `json:"jalan"`
	Rt         sql.NullString `json:"rt"`
	Rw         sql.NullString `json:"rw"`
	Kota       sql.NullString `json:"kota"`
	PostalCode sql.NullString `json:"postal_code"`
}

func (q *Queries) UpdateAddress(ctx context.Context, arg UpdateAddressParams) error {
	_, err := q.db.ExecContext(ctx, UpdateAddress,
		arg.ID,
		arg.Jalan,
		arg.Rt,
		arg.Rw,
		arg.Kota,
		arg.PostalCode,
	)
	return err
}
