// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: permissions.sql

package sqlc

import (
	"context"
)

const GetPermissionsByRoleID = `-- name: GetPermissionsByRoleID :many
SELECT p.id, p.name
FROM permissions p
JOIN roles_permissions rp ON rp.permission_id = p.id
WHERE rp.role_id = $1
`

func (q *Queries) GetPermissionsByRoleID(ctx context.Context, roleID int64) ([]*Permission, error) {
	rows, err := q.db.QueryContext(ctx, GetPermissionsByRoleID, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Permission{}
	for rows.Next() {
		var i Permission
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetPermissionsByUserID = `-- name: GetPermissionsByUserID :many
SELECT DISTINCT p.id, p.name
FROM permissions p
JOIN roles_permissions rp ON rp.permission_id = p.id
JOIN user_roles ur ON ur.roles_id = rp.role_id
WHERE ur.user_id = $1
`

func (q *Queries) GetPermissionsByUserID(ctx context.Context, userID int64) ([]*Permission, error) {
	rows, err := q.db.QueryContext(ctx, GetPermissionsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Permission{}
	for rows.Next() {
		var i Permission
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
