// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

type Address struct {
	ID         int32  `json:"id"`
	Jalan      string `json:"jalan"`
	Rt         string `json:"rt"`
	Rw         string `json:"rw"`
	Kota       string `json:"kota"`
	PostalCode string `json:"postal_code"`
}

type Permission struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

type Role struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

type RolesPermission struct {
	ID           int64 `json:"id"`
	RoleID       int64 `json:"role_id"`
	PermissionID int64 `json:"permission_id"`
}

type User struct {
	ID        int32  `json:"id"`
	Name      string `json:"name"`
	Email     string `json:"email"`
	Password  string `json:"password"`
	CreatedAt int64  `json:"created_at"`
	UpdatedAt int64  `json:"updated_at"`
}

type UserRole struct {
	ID      int64 `json:"id"`
	UserID  int64 `json:"user_id"`
	RolesID int64 `json:"roles_id"`
}
