// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: roles.sql

package sqlc

import (
	"context"
	"database/sql"
)

const AssignRoleToUser = `-- name: AssignRoleToUser :exec
INSERT INTO user_roles (user_id, roles_id)
VALUES ($1, $2)
`

type AssignRoleToUserParams struct {
	UserID  int64 `json:"user_id"`
	RolesID int64 `json:"roles_id"`
}

func (q *Queries) AssignRoleToUser(ctx context.Context, arg AssignRoleToUserParams) error {
	_, err := q.db.ExecContext(ctx, AssignRoleToUser, arg.UserID, arg.RolesID)
	return err
}

const GetRolesByUserID = `-- name: GetRolesByUserID :many
SELECT r.id, r.name
FROM roles r
JOIN user_roles ur ON ur.roles_id = r.id
WHERE ur.user_id = $1
`

func (q *Queries) GetRolesByUserID(ctx context.Context, userID int64) ([]*Role, error) {
	rows, err := q.db.QueryContext(ctx, GetRolesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Role{}
	for rows.Next() {
		var i Role
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetRolesWithPermissionsByUserID = `-- name: GetRolesWithPermissionsByUserID :many
SELECT 
    r.id AS role_id,
    r.name AS role_name,
    p.id AS permission_id,
    p.name AS permission_name
FROM user_roles ur
JOIN roles r ON r.id = ur.roles_id
LEFT JOIN roles_permissions rp ON rp.role_id = r.id
LEFT JOIN permissions p ON p.id = rp.permission_id
WHERE ur.user_id = $1
ORDER BY r.id, p.name
`

type GetRolesWithPermissionsByUserIDRow struct {
	RoleID         int32          `json:"role_id"`
	RoleName       string         `json:"role_name"`
	PermissionID   sql.NullInt32  `json:"permission_id"`
	PermissionName sql.NullString `json:"permission_name"`
}

func (q *Queries) GetRolesWithPermissionsByUserID(ctx context.Context, userID int64) ([]*GetRolesWithPermissionsByUserIDRow, error) {
	rows, err := q.db.QueryContext(ctx, GetRolesWithPermissionsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetRolesWithPermissionsByUserIDRow{}
	for rows.Next() {
		var i GetRolesWithPermissionsByUserIDRow
		if err := rows.Scan(
			&i.RoleID,
			&i.RoleName,
			&i.PermissionID,
			&i.PermissionName,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const RemoveRoleFromUser = `-- name: RemoveRoleFromUser :exec
DELETE FROM user_roles
WHERE user_id = $1 AND roles_id = $2
`

type RemoveRoleFromUserParams struct {
	UserID  int64 `json:"user_id"`
	RolesID int64 `json:"roles_id"`
}

func (q *Queries) RemoveRoleFromUser(ctx context.Context, arg RemoveRoleFromUserParams) error {
	_, err := q.db.ExecContext(ctx, RemoveRoleFromUser, arg.UserID, arg.RolesID)
	return err
}
