// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"
)

const CountUserByID = `-- name: CountUserByID :one
SELECT COUNT(*) FROM users WHERE id = $1
`

func (q *Queries) CountUserByID(ctx context.Context, id int32) (int64, error) {
	row := q.db.QueryRowContext(ctx, CountUserByID, id)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CountUserByName = `-- name: CountUserByName :one
SELECT COUNT(*) FROM users WHERE name = $1
`

func (q *Queries) CountUserByName(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRowContext(ctx, CountUserByName, name)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const CreateUser = `-- name: CreateUser :one
INSERT INTO users (name, email, password, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type CreateUserParams struct {
	Name      string `json:"name"`
	Email     string `json:"email"`
	Password  string `json:"password"`
	CreatedAt int64  `json:"created_at"`
	UpdatedAt int64  `json:"updated_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, CreateUser,
		arg.Name,
		arg.Email,
		arg.Password,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const FindUserByEmail = `-- name: FindUserByEmail :one
SELECT id, name, email, password, created_at, updated_at 
FROM users WHERE email = $1
`

func (q *Queries) FindUserByEmail(ctx context.Context, email string) (*User, error) {
	row := q.db.QueryRowContext(ctx, FindUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const FindUserByID = `-- name: FindUserByID :one
SELECT id, name, email, password, created_at, updated_at
FROM users
WHERE id = $1
`

func (q *Queries) FindUserByID(ctx context.Context, id int32) (*User, error) {
	row := q.db.QueryRowContext(ctx, FindUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
