CREATE TABLE IF NOT EXISTS address (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    jalan VARCHAR(100) NOT NULL,
    rt VARCHAR(100) NOT NULL,
    rw VARCHAR(100) NOT NULL,
    kelurahan VARCHAR(100) NOT NULL,
    kecamatan VARCHAR(100) NOT NULL,
    kota VARCHAR(100) NOT NULL,
    provinsi VARCHAR(100) NOT NULL,
    kode_pos VARCHAR(100) NOT NULL
);