CREATE TABLE IF NOT EXISTS address (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    jalan VARCHAR(255) NOT NULL,
    rt VARCHAR(255) UNIQUE NOT NULL,
    rw VARCHAR(255) NOT NULL,
    kota VARCHAR(255) NOT NULL,
    postal_code VARCHAR(255) UNIQUE NOT NULL,
);
