// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"context"
)

type Querier interface {
	CountUserByID(ctx context.Context, id int32) (int64, error)
	CountUserByName(ctx context.Context, name string) (int64, error)
	CreateAddress(ctx context.Context, arg CreateAddressParams) (int32, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (int32, error)
	FindAdressByID(ctx context.Context, id int32) (*Address, error)
	FindUserByEmail(ctx context.Context, email string) (*User, error)
	FindUserByID(ctx context.Context, id int32) (*User, error)
	FindUserRolesWithPermissions(ctx context.Context, userID int64) ([]*FindUserRolesWithPermissionsRow, error)
	UpdateAddress(ctx context.Context, arg UpdateAddressParams) error
}

var _ Querier = (*Queries)(nil)
